[package]
name = "hyper-socks2"
version = "0.4.0"
authors = ["Arsenii Lyashenko <arsenylyashenko.3@gmail.com>"]
license = "Apache-2.0 OR MIT"
description = "A SOCKS5 connector for hyper library"
repository = "https://github.com/ark0f/hyper-socks2"
documentation = "https://docs.rs/hyper-socks2"
readme = "README.md"
keywords = ["hyper", "network", "ssl", "tls"]
categories = ["authentication", "network-programming", "web-programming::http-client"]
include = ["Cargo.toml", "LICENSE-*.md", "src/**/*"]
edition = "2018"

[badges]
github-actions = { repository = "https://github.com/ark0f/hyper-socks2", workflow = "CI" }

[dependencies]
hyper = "0.13"
async-socks5 = "0.3"
futures = "0.3"
tokio = { version = "0.2", features = ["net", "tcp"] }
thiserror = "1.0.9"
http = "0.2"

# `tls` feature
hyper-tls = { version = "0.4", optional = true }

[dev-dependencies]
tokio = { version = "0.2", features = ["net", "tcp", "macros"] }

[features]
default = ["tls"]
tls = ["hyper-tls"]
